/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.text.MessageFormat;

/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./hw03-gradle/build/libs/gradleTesting-0.1.jar ru.otus.SampleTest
 *
 */
public class Testing {
    public  Testing() {
    }

    public static void main(String... args) {
        String testClassName =  args[0]; //"ru.otus.Testing";

        try {
            var testClass = Class.forName(testClassName);
            var tests = TestClassParser.extractTestsFromClass(testClass.getDeclaredMethods());

            for (var test: tests) {
               Runner.run(testClass, test);
            }
        } catch (Exception e) {
            System.out.println(MessageFormat.format("Failed to process {0}: {1}",
                    testClassName,
                    e.toString()));
        }
    }
}
