version: "3.8"
services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: demoDB
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: my@email.com
      PGADMIN_DEFAULT_PASSWORD: pwd